const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const Module=require('module');const fs=require('fs');
const React=require('react');const {create,act}=require('react-test-renderer');global.IS_REACT_ACT_ENVIRONMENT=true;
const values=new Map();const storage={getItem:async k=>values.get(k)||null,setItem:async(k,v)=>values.set(k,v),removeItem:async k=>values.delete(k)};
const original=Module._load;
Module._load=function(id,...args){
 if(id==='expo-secure-store')return {getItemAsync:storage.getItem,setItemAsync:storage.setItem,deleteItemAsync:storage.removeItem};
 if(id==='@react-native-async-storage/async-storage')return {__esModule:true,default:storage};
 if(id==='react-native')return {View:'View',Text:'Text',ScrollView:'ScrollView',TouchableOpacity:'TouchableOpacity',TextInput:'TextInput',Image:'Image',ActivityIndicator:'ActivityIndicator',StyleSheet:{create:x=>x},Platform:{OS:'ios'},Alert:{alert:()=>{}},Share:{},Keyboard:{dismiss:()=>{}},ActionSheetIOS:{},Animated:{View:'AnimatedView',Value:class {constructor(v){this.value=v;}},spring:()=>({start:()=>{}})},Modal:({visible,children})=>visible?React.createElement('Modal',{},children):null};
 if(id==='react-native-keyboard-aware-scroll-view')return {KeyboardAwareScrollView:'ScrollView'};
 if(id==='react-native-safe-area-context')return {SafeAreaView:'SafeAreaView'};
 if(id==='@expo/vector-icons')return {Ionicons:'Icon'};
 if(id==='expo-blur')return {BlurView:'BlurView'};
 if(id==='expo-haptics')return {impactAsync:async()=>{},selectionAsync:async()=>{},notificationAsync:async()=>{},ImpactFeedbackStyle:{Light:'light',Medium:'medium'},NotificationFeedbackType:{Success:'success'}};
 if(id==='expo-router')return {useRouter:()=>({push:()=>{}})};
 if(id.endsWith('/settingsStore'))return {useSettingsStore:{getState:()=>({gatewayUrl:'https://test.invalid',gatewayToken:'synthetic'})}};
 if(id.endsWith('/patientSync'))return {syncPatients:async()=>({success:true})};
 if(id.endsWith('/dictationSync'))return {syncFinalizedDictations:async()=>({success:true})};
 if(id.endsWith('/usePatientVoiceInput'))return {usePatientVoiceInput:()=>({})};
 if(id.endsWith('/usePatientScan'))return {usePatientScan:()=>({})};
 return original.call(this,id,...args);
};
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText,file);
const Screen=require('../app/(tabs)/patients.tsx').default;
const {usePatientsStore:store}=require('../src/stores/patientsStore.ts');
test('fresh installation: Add patient opens form, Save creates and displays patient immediately',async()=>{
 await store.persist.rehydrate();let tree;await act(async()=>{tree=create(React.createElement(Screen));});
 assert.match(JSON.stringify(tree.toJSON()),/Restore saved cases/);
 const add=tree.root.findAllByType('TouchableOpacity').find(x=>x.props.accessibilityLabel==='Add patient');
 await act(async()=>add.props.onPress());
 assert.equal(tree.root.findAllByType('Modal').length,1);
 const modal=tree.root.findByType('Modal');
 const inputs=modal.findAllByType('TextInput');
 const name=inputs.find(x=>x.props.placeholder==='Last, First');
 const mrn=inputs.find(x=>/MRN|Medical record/i.test(x.props.placeholder||''));
 assert.ok(name);assert.ok(mrn);
 await act(async()=>name.props.onChangeText('Synthetic Patient'));
 await act(async()=>mrn.props.onChangeText('TEST-ONLY'));
 const save=modal.findAllByType('TouchableOpacity').find(x=>x.findAllByType('Text').some(t=>t.props.children==='Save'));
 await act(async()=>save.props.onPress());
 assert.equal(tree.root.findAllByType('Modal').length,0);
 assert.equal(Object.values(store.getState().patients)[0].name,'Synthetic Patient');
 assert.match(JSON.stringify(tree.toJSON()),/Synthetic Patient/);
 await act(async()=>tree.unmount());
});
